---
variables:
  NAMESPACE: "t5g-web"
  IMAGE: "t5gweb"
  TAG: "latest"  # $CI_PIPELINE_IID

stages:
  - sync

github_sync:
  stage: sync
  script:
    - git config --global user.email "${GL_USER_EMAIL}"
    - git config --global user.name "${GL_USER}"
    - git clone git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git
    - cd t5g-field-support-team-utils
    - git remote add upstream https://$GH_USER:$GH_PASS@github.com/RHsyseng/t5g-field-support-team-utils.git
    - git fetch upstream
    - git checkout master
    - git merge upstream/main --allow-unrelated-histories
    - git push origin master
    - echo "Sync has completed"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
